# 172.16.17.51:9200
elasticsearch:
    schema: http
    host: 192.168.40.220
    port: 9200
log:
    path: logs
    name: traceinit.log
    level: INFO

db:
  host: localhost
  port: 3306
  user: root
  password: 807429
  db_name: alvin
  db_type: mysql
